version: "3.8"
services:
  backend:
    build:
      context: ../
      dockerfile: dockerfiles/Dockerfile
      # target: production
    container_name: backend
    ports:
      - 8000:8000
    depends_on: 
      - database
    command: "python manage.py runserver 0.0.0.0:8000"


  database:
    image: postgres:12.16
    container_name: database
    expose:
      - "5432"

